[package]
name = "rush"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rush-base = { path = "./crates/rush-base", version = "0.1.0" }
argparse = "0.2.2"
