[package]
name = "rush"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "9.1.2"
argparse = "0.2.2"
call_command = { path = "./crates/call_command", version = "0.0.0" }
shell-props = { path = "./crates/shell-props", version = "0.0.0" }