[package]
name = "rush-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rush-utils = { path = "../rush-utils", version = "0.1.0" }

derive_builder = "0.11.2"
lazy_static = "1.4.0"